services:
  seghandwriting-app:
    build:
      context: .
      dockerfile: build/Dockerfile.tesla-m40  # 使用特制Dockerfile
    image: seghandwriting-app:latest
    container_name: seghandwriting-app
    ports:
      - "8040:8040"  # VisualDL 服务端口
    volumes:
      - ./data:/app/data
      - ./work:/app/work
      - ./models:/app/models  # 挂载模型和日志目录
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./gpu_check.py:/app/gpu_check.py
      - ./data_processor.py:/app/data_processor.py
      - ./train_demo.py:/app/train_demo.py
    environment:
      # 数据集压缩包所在目录（映射到宿主机 ./data 目录）
      - DATA_ROOT=/app/data
      # 数据集解压目标目录（映射到宿主机 ./work/data 目录）
      - EXTRACT_ROOT=/app/work/data
    runtime: nvidia
    tty: true
    stdin_open: true
    command: /bin/bash -c "/app/entrypoint.sh"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
